### ISSUE TITLE
error: 'Base64' was not declared in this scope

### ISSUE THREAD

**Issue by edwardcorke** [Xander-Electronics/Base64#12]
Running on an ESP32 and simply trying to compile the encode example however Base64 is not found in scope

> error: 'Base64' was not declared in this scope

`Base64.encodedLength(inputStringLength);`

**Comment by aaroned** [comment]
@edwardcorke I had the same issue, and discovered the ESP32 Arduino core already has a base64 implementation. Simply use: 

`#include <base64.h>`

**Comment by lucasroth** [comment]
@edwardcorke I was going crazy with this issue also. I copied the base64 library files (.h and .cpp) to the project folder and worked fine. Some base64 libraries don´t have al the functions inside, just check the .h file, for example: base64_enc_len exists.

**Comment by agdl** [comment]
Closing this :)
