### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by TiMESPLiNTER** [Xander-Electronics/Base64#14]
I need the change introduced in this commit `a3e5384ca51d1307c0e6e4291ea73bd7dd7b0fdb`. (PR: #10 )

It's in master but unfortunately there has not been a release since the change has been committed. 

Is it planned to create a new release soon including this change?

**Comment by norcino** [comment]
Thank you TiMESPLiNTER I fixed an issue in my code tanks to your changes.
I was having error showing file not found `pgmspace.h`.
Adding your change manually in my downloaded Base64.cpp fixed my issue.
