### ISSUE TITLE
Library does not compile for ESP8266

### ISSUE THREAD

**Issue by rin67630** [Xander-Electronics/Base64#9]
Compiling the provided examples with the Arduino IDE will fail, when the processor is an ESPxxxx.

exit status 1
'Base64' was not declared in this scope

**Comment by rin67630** [comment]
@jandre-d 
Thank you!

**Comment by aaroned** [comment]
@rin67630 I had the same issue and discovered the Arduino core for the ESPxxxx already includes a base64 implementation. All that's needed is:

`#include <base64.h>`

**Comment by rin67630** [comment]
@aaroned 

Great!
